create database if not EXISTS portfolio_db;
USE portfolio_db;
CREATE TABLE IF NOT EXISTS assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  exchange VARCHAR(50) NOT NULL,
  current_price DECIMAL(18, 4) DEFAULT NULL,
  price_updated_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historical_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL, 
  date_time DATETIME NOT NULL,
  interval_type VARCHAR(10) NOT NULL, 
  open DECIMAL(15, 4) NOT NULL, 
  high DECIMAL(15, 4) NOT NULL, 
  low DECIMAL(15, 4) NOT NULL, 
  close DECIMAL(15, 4) NOT NULL, 
  volume BIGINT, 

  FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,

  UNIQUE KEY unique_historical (asset_id, date_time, interval_type)
);


CREATE TABLE IF NOT EXISTS portfolios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL COMMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT,
  UNIQUE KEY uk_name (name) COMMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS portfolio_assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  asset_id INT NOT NULL,
  quantity DECIMAL(18, 6) NOT NULL,
  buy_price DECIMAL(18, 4) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE,
  FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
  UNIQUE KEY uk_portfolio_asset (portfolio_id, asset_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
